import React from 'react'
import "./description.css"

const GoogleAdsDescription = () => {
  return (
    <section id='descripions'>
        <div className="container descripion__container">
            <div className="description__wrapper">
                <div className="des__top">
                    <h2>Why You Need Google Ads</h2>
                    <p>In today's competitive digital landscape, Google Ads is a game-changer. It puts your brand in front of potential customers when they are actively searching for products or services like yours. </p>
                    <p>With Google Ads, you can increase your online visibility, drive qualified leads, and boost conversions. It's the fastest way to reach your target audience and outshine your competitors..</p>
                </div>
                <hr />
                <div className="des__midddle">
                    <h2>Our Process Is Seamless</h2>
                    <div className="action">
                        <div className="acion__one">
                            <h4>Order</h4>
                            <p>Simply provide us with your project details, campaign objectives, target audience, and budget preferences. Our dedicated team will take it from there, handling every aspect of your Google Ads campaign with precision.</p>
                        </div>
                        <div className="acion__two">
                            <h4>Expert Campaign Setup and Optimization:</h4>
                            <p>We conduct extensive keyword research, ad creation, and strategic bidding to ensure maximum visibility and optimal performance. </p>
                        </div>
                        <div className="acion__three">
                            <h4>Reporting and Analytics</h4>
                            <p>Our detailed analytics reveal valuable insights into impressions, clicks, conversions, cost-per-click (CPC), and other relevant metrics to help you track your campaign's success, and understand the tangible results generated by our efforts.</p>
                        </div>
                    </div>
                </div>
                <hr />
                <div className="dec__bottom">
                    <h2>Google Is Our Pal So You’re Guaranteed</h2>
                    <div className="job">
                        <div className="job__one">
                            <h4>Increase Awareness</h4>
                            <p>Elevate your brand presence and capture the attention of your target audience with eye-catching visuals that leave a mark.</p>
                        </div>
                        <div className="job__two">
                            <h4>Tailored Strategies</h4>
                            <p>We'll create a customized social media strategy based on your business goals, target audience, and industry to help you achieve the results you want. </p>
                        </div>
                        <div className="job__three">
                            <h4>High Conversion</h4>
                            <p>We craft strategic messages and captivating visuals that compel viewers to take action, thus driving higher click-through rates (CTR), increased conversions, and a high ROAS.</p>
                        </div>
                        <div className="job__four">
                            <h4>Cost-Effective Creatives</h4>
                            <p>Experience the power of cost-effective creatives that deliver exceptional results. We leverage innovative approaches and ad formats within the Google Ads ecosystem, such as TrueView ads and responsive display ads. </p>
                        </div>
                        <div className="job__five">
                            <h4>Transparent reporting </h4>
                            <p>We provide comprehensive and easy-to-understand reports covering impressions, clicks, conversions, cost-per-click (CPC), and other relevant metrics.</p>
                        </div>
                        <div className="job__five">
                            <h4>Results</h4>
                            <p>Whether it's increasing website traffic, generating leads, or boosting conversions, we prioritize outcomes that align with your specific objectives. </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
  )
}

export default GoogleAdsDescription